export default {
  pages: [
    'pages/web/login/index',
    'pages/web/dashboard/index',
    'pages/web/purchases/index',
    'pages/web/purchases/new',
    'pages/web/purchases/[id]',
    'pages/web/sales/index',
    'pages/web/sales/new',
    'pages/web/sales/[id]',
    'pages/web/inventory/index',
    'pages/web/inventory/stocktake',
    'pages/web/inventory/transfer',
    'pages/web/products/index',
    'pages/web/categories/index',
    'pages/web/suppliers/index',
    'pages/web/customers/index',
    'pages/web/warehouses/index',
    'pages/web/reports/index',
    'pages/web/settings/index',
    'pages/web/settings/users',
    'pages/web/settings/roles',
    'pages/mini/index/index',
    'pages/mini/scan/index',
    'pages/mini/voice/index',
    'pages/mini/photo/index',
    'pages/mini/purchase/index',
    'pages/mini/sale/index',
    'pages/mini/orders/list',
    'pages/mini/orders/detail',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '进销存',
    navigationBarTextStyle: 'black'
  }
};
